---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-srl-config-ndd-yndd-io-v1alpha1-srlconfig
  failurePolicy: Fail
  name: validate.srl.config.ndd.yndd.io
  rules:
  - apiGroups:
    - srl.config.ndd.yndd.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  sideEffects: None
